//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theResearchSite.creditCardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="creditCardService.creditServiceSoap")]
    public interface creditServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creditCardCheck", ReplyAction="*")]
        int creditCardCheck(int businessId, int creditNumberOfCostumer, int amount, System.DateTime CardexpireDate, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/creditCardCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<int> creditCardCheckAsync(int businessId, int creditNumberOfCostumer, int amount, System.DateTime CardexpireDate, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowMoneyAmount", ReplyAction="*")]
        int ShowMoneyAmount(int bussinesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowMoneyAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ShowMoneyAmountAsync(int bussinesId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface creditServiceSoapChannel : theResearchSite.creditCardService.creditServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class creditServiceSoapClient : System.ServiceModel.ClientBase<theResearchSite.creditCardService.creditServiceSoap>, theResearchSite.creditCardService.creditServiceSoap {
        
        public creditServiceSoapClient() {
        }
        
        public creditServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public creditServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public creditServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public creditServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int creditCardCheck(int businessId, int creditNumberOfCostumer, int amount, System.DateTime CardexpireDate, int userId) {
            return base.Channel.creditCardCheck(businessId, creditNumberOfCostumer, amount, CardexpireDate, userId);
        }
        
        public System.Threading.Tasks.Task<int> creditCardCheckAsync(int businessId, int creditNumberOfCostumer, int amount, System.DateTime CardexpireDate, int userId) {
            return base.Channel.creditCardCheckAsync(businessId, creditNumberOfCostumer, amount, CardexpireDate, userId);
        }
        
        public int ShowMoneyAmount(int bussinesId) {
            return base.Channel.ShowMoneyAmount(bussinesId);
        }
        
        public System.Threading.Tasks.Task<int> ShowMoneyAmountAsync(int bussinesId) {
            return base.Channel.ShowMoneyAmountAsync(bussinesId);
        }
    }
}
